export const LOGIN_START = "LOGIN_START";
export const LOGIN_START_SUCCESS = "LOGIN_START_SUCCESS";
export const LOGIN_START_ERROR = "LOGIN_START_ERROR";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_START_SUCCESS = "LOGOUT_START_SUCCESS";
export const LOGOUT_START_ERROR = "LOGOUT_START_ERROR";

export const GET_POSTS_START = "GET_POSTS_START";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";

export const GET_COMMENTS_START = "GET_COMMENTS_START";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR";

export const GET_AUTHOR_START = "GET_AUTHOR_START";
export const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
export const GET_AUTHOR_ERROR = "GET_AUTHOR_ERROR";

export const GET_TAGS_START = "GET_TAGS_START";
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_ERROR = "GET_TAGS_ERROR";

export const CLEAN_MESSAGE = "CLEAN_MESSAGE";
export const CLEAN_MESSAGE_APP = "CLEAN_MESSAGE_APP";